mysql:
    connection: mysql+mysqlconnector://root:getit@123@localhost/MailShot

logfile: "MailShot.log"
errorlogfile: "MailShotError.log"

redis:
    host: localhost
    port: 6379
    db: 7
    queue: mailshot_scheduler

email_worker_threads_count: 20

aws_access_key_id: AKIAI2ZNLE7EET4LHENQ
aws_secret_access_key: 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
aws_region: eu-west-1
self_url: http://localhost:9048/campaign/v1
mail_sender: ruchi@askme.in