mysql:
    connection: mysql+mysqlconnector://askme:ma8ho2n3qdy9ew@new-rds-askme.c0wj8qdslqom.ap-southeast-1.rds.amazonaws.com/cantor

logfile: "/var/log/cantor/Catalog.log"
errorlogfile: "/var/log/cantor/CatalogError.log"

redis:
    host: redis-userservice.6h3jqd.0001.apse1.cache.amazonaws.com
    port: 6379
    db: 7
    queue: mailshot_scheduler

email_worker_threads_count: 20
